vars: {
  d2-config: {
    sketch: true
    theme-id: 200
  }
}

main loop -> Downloader: spawn task
main loop -> StreamReader: add to queue
Downloader -> StreamProgress: update progress
StreamReader -> StreamProgress: request position
StreamProgress -> StreamReader: notify progress
